### PR TITLE
New config parameter and MySQLdb version dataConnection

### PR DESCRIPTION
**Pull request by royxue**
Add tablename into config.ini
Add MySQLdb version dataConnection
Test passed

### CODE REVIEW

**Comment by julian-ramos** [comment]
Tablename should not be in the configuration since it depends on the short
term task. Only long term parameters should be on the config file.

Please revert changes for tablename.

Thanks,

On Mon, Feb 9, 2015 at 4:59 AM, Roy Xue notifications@github.com wrote:

> Add tablename into config.ini
> Add MySQLdb version dataConnection
> 
> ## Test passed
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/julian-ramos/awareAnalysis/pull/5
> Commit Summary
> - PEP8 code style reformat
> - Add tablename to config.ini
> - Total apply config file
> - Add MySQLdb version data connection
> 
> File Changes
> - _M_ config.ini
>   https://github.com/julian-ramos/awareAnalysis/pull/5/files#diff-0
>   (9)
> - _M_ databaseConnection.py
>   https://github.com/julian-ramos/awareAnalysis/pull/5/files#diff-1
>   (137)
> - _A_ databseConnection_MySQLdb.py
>   https://github.com/julian-ramos/awareAnalysis/pull/5/files#diff-2
>   (122)
> - _M_ playground.py
>   https://github.com/julian-ramos/awareAnalysis/pull/5/files#diff-3
>   (41)
> - _M_ staticAndroid.py
>   https://github.com/julian-ramos/awareAnalysis/pull/5/files#diff-4
>   (45)
> - _M_ usersAnalysis.py
>   https://github.com/julian-ramos/awareAnalysis/pull/5/files#diff-5
>   (544)
> 
> Patch Links:
> - https://github.com/julian-ramos/awareAnalysis/pull/5.patch
> - https://github.com/julian-ramos/awareAnalysis/pull/5.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/julian-ramos/awareAnalysis/pull/5.

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
My original idea of why I did this is that though tablename is kinda short term, it's a config parameter. In previous version, if people wanna change tablename, they need to modify the variables in .py files. But if we put it in config file, people will be able to make changes without doing anything in our source code(beginner would make mistakes dealing with the source.) 
On the other hand, python ConfigParser has some advantaged usage, when we run scripts, we could run like CONFIG=tablename='xxx' to overwrite config value in the config file(For now, this function havent been added to our repo).

**Comment by julian-ramos** [comment]
yes I want the explicit change in the .py file and I don't want that
parameter on the config file.

Tablename sometimes is input sometimes is output so it has to be specified
separately in each case and not from the config file.

Your concern about people dealing with the source code is unfounded since
the idea is that they can access this as a module. In fact we should start
having a separate .py and not the way I have it using if __name_ ..... that
should be used just for quick tests.

On Tue, Feb 10, 2015 at 5:27 AM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> My original idea of why I did this is that though tablename is kinda short
> term, it's a config parameter. In previous version, if people wanna change
> tablename, they need to modify the variables in .py files. But if we put it
> in config file, people will be able to make changes without doing anything
> in our source code(beginner would make mistakes dealing with the source.)
> On the other hand, python ConfigParser has some advantaged usage, when we
> run scripts, we could run like CONFIG=tablename='xxx' to overwrite config
> value in the config file(For now, this function havent been added to our
> repo).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/julian-ramos/awareAnalysis/pull/5#issuecomment-73677139
> .

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
hmmm, this is ok, I will revert changes. 
separate test file is needed, as well as a test database(make sure the test could finish within short time).

**Comment by julian-ramos** [comment]
the other changes in that pull are fine.

Once this is done let me know and I will share with you the output tables
to compare against the last version of the code

On Tue, Feb 10, 2015 at 5:46 AM, Roy Xue notifications@github.com wrote:

> @julian-ramos https://github.com/julian-ramos
> hmmm, this is ok, I will revert changes.
> separate test file is needed, as well as a test database(make sure the
> test could finish within short time).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/julian-ramos/awareAnalysis/pull/5#issuecomment-73679667
> .

## 

Julian.

**Comment by royxue** [comment]
@julian-ramos 
revert is done

**Pull request merged**
